// <auto-generated />
namespace DataAcsesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_yak : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_yak));
        
        string IMigrationMetadata.Id
        {
            get { return "202307082108590_mig_yak"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
